apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: recurring-events
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 259200000  # 3 days retention (recurring tasks)
    segment.bytes: 1073741824  # 1 GiB
    cleanup.policy: compact,delete