apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: reminder-events
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000  # 1 day retention (reminders are time-sensitive)
    segment.bytes: 1073741824  # 1 GiB
    cleanup.policy: delete